import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";
import {
  Color4T,
  DrawingSlotT,
  DrawingT,
  FrameT,
  GpenT,
  IndexRangeT,
  LayerGroupT,
  LayerT,
  LayerTreeNodeT,
  MaterialSlotT,
  Matrix4x4F32T,
  PointFlagsT,
  PointT,
  StrokeAnchorT,
  StrokeFlagsT,
  StrokeT,
  Vec2T,
  Vec3T,
} from "gpen-protocol/flatbuffers";

import { decodeGpen } from "../src/lib/bindings/flatbuffers/codec";
import { NONE_INDEX } from "../src/lib/bindings/flatbuffers/constants";

/**
 * Cross-runtime fixtures generated by gpen-protocol:
 *
 *   cd ../gpen-protocol && npm run build:fixtures
 *
 * Every .bin was produced by flatc 25.12.19 (via flatc-wasm) from the .json
 * files in `gpen-protocol/fixtures/gpen/v1` and round-trip verified against
 * the same schema. Decoding them with the JS codec proves the JS accessors
 * agree with the flatc-wasm JSON pipeline and the Zig accessors (which decode
 * the same .bin files in gpen-zig/src/proto_test.zig).
 */
// Resolved from this test file's directory (tests/), independent of the
// process CWD: tests/ -> ../../gpen-protocol/fixtures/gpen/v1
const FIXTURES_DIR = join(import.meta.dir, "../../gpen-protocol/fixtures/gpen/v1");

/**
 * Build a generated `*T` object from a partial literal. The generated object
 * API uses constructor parameter properties, so plain `Object.assign` over a
 * `new T()` keeps every default and avoids unreadable positional arguments.
 */
function make<T>(ctor: new () => T, init: Record<string, unknown>): T {
  const target = new ctor();
  for (const [key, value] of Object.entries(init)) {
    (target as Record<string, unknown>)[key] = value;
  }
  return target;
}

/** Exact float32 coercion: FlatBuffers f32 accessors round-trip with precision loss otherwise. */
const float32 = (value: number) => new Float32Array([value])[0];

function loadFixture(name: string): Uint8Array {
  return readFileSync(`${FIXTURES_DIR}/${name}`);
}

const emptyDocument = make(GpenT, {
  drawings: [],
  nodes: [],
  layers: [],
  groups: [],
  materials: [],
  activeNodeIndex: NONE_INDEX,
  onionSkinningSettings: null,
  flags: null,
  childIndices: [],
});

function fullDocument(): GpenT {
  return make(GpenT, {
    ...emptyDocument,
    drawings: [
      make(DrawingSlotT, {
        drawing: make(DrawingT, {
          type: 0,
          strokes: [
            make(StrokeT, {
              points: [
                make(PointT, {
                  x: 10,
                  y: 20,
                  z: 0,
                  radius: 2,
                  opacity: 1,
                  pressure: float32(0.75),
                  time: 0,
                  rotation: 0,
                  vertexColor: make(Color4T, { r: 1, g: float32(0.5), b: float32(0.25), a: 1 }),
                  flags: make(PointFlagsT, { selected: false, locked: false, filled: false }),
                  tilt: make(Vec2T, { x: 2, y: -3 }),
                  twist: 45,
                  pointerType: 2,
                  timestamp: 1234.5,
                  miterAngle: 0,
                  handleLeft: null,
                  handleRight: null,
                  handleTypeLeft: 0,
                  handleTypeRight: 0,
                  nurbsWeight: 1,
                }),
              ],
              curveType: 0,
              materialIndex: 0,
              startCap: 0,
              endCap: 1,
              softness: 0,
              fillColor: make(Color4T, { r: 0, g: 0, b: 0, a: 0 }),
              fillId: 0,
              flags: make(StrokeFlagsT, {
                cyclic: false,
                selected: false,
                hidden: false,
                fillVisible: true,
              }),
              id: "stroke-1",
              initTime: 0,
              fillOpacity: 0,
              aspectRatio: 1,
              uScale: 1,
              uvRotation: 0,
              uvTranslation: make(Vec2T, { x: 0, y: 0 }),
              uvScale: make(Vec2T, { x: 1, y: 1 }),
              uTranslation: 0,
              anchor: make(StrokeAnchorT, {
                coordinateSpace: 2,
                documentId: "doc-1",
                framePath: "top",
                transform: make(Matrix4x4F32T, {
                  elements: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
                }),
                scrollOffset: make(Vec2T, { x: 0, y: 0 }),
                devicePixelRatio: 2,
                pageZoom: 1,
              }),
              resolution: 0,
              nurbsOrder: 0,
              nurbsKnotMode: 0,
              customKnots: [],
            }),
          ],
        }),
        reference: null,
      }),
    ],
    nodes: [
      make(LayerTreeNodeT, {
        name: "Root",
        type: 1,
        itemIndex: 0,
        parentIndex: NONE_INDEX,
        color: make(Vec3T, { x: 0, y: 0, z: 0 }),
        flags: null,
      }),
      make(LayerTreeNodeT, {
        name: "Ink",
        type: 0,
        itemIndex: 0,
        parentIndex: 0,
        color: make(Vec3T, { x: float32(0.1), y: float32(0.2), z: float32(0.3) }),
        flags: null,
      }),
    ],
    layers: [
      make(LayerT, {
        name: "Ink",
        type: 0,
        itemIndex: 0,
        parentIndex: 0,
        color: make(Vec3T, { x: float32(0.1), y: float32(0.2), z: float32(0.3) }),
        flags: null,
        frames: [
          make(FrameT, { frameNumber: 1, drawingIndex: 0, type: 0, flags: null, isEnd: false }),
        ],
        masks: [],
        blendMode: 0,
        opacity: 1,
        parent: null,
        transform: null,
        parentInverse: null,
        viewLayerName: "",
        activeMaskIndex: NONE_INDEX,
        passIndex: 0,
        tintColor: null,
        radiusOffset: 0,
      }),
    ],
    groups: [
      make(LayerGroupT, {
        name: "Root",
        type: 1,
        itemIndex: 0,
        parentIndex: NONE_INDEX,
        color: make(Vec3T, { x: 0, y: 0, z: 0 }),
        flags: null,
        childRange: make(IndexRangeT, { start: 0, len: 1 }),
        colorTag: 0,
      }),
    ],
    materials: [
      make(MaterialSlotT, {
        name: "Ink",
        strokeColor: make(Color4T, { r: 0, g: 0, b: 0, a: 1 }),
        fillColor: make(Color4T, { r: 0, g: 0, b: 0, a: 0 }),
        mode: 0,
        flags: null,
      }),
    ],
    activeNodeIndex: 1,
    childIndices: [1],
  });
}

describe("protocol fixtures (flatc-generated .bin)", () => {
  test("minimal.bin decodes to an empty document with the active sentinel", () => {
    expect(decodeGpen(loadFixture("minimal.bin"))).toEqual(emptyDocument);
  });

  test("full.bin decodes to the complete layer/stroke/anchor document", () => {
    const document = decodeGpen(loadFixture("full.bin"));
    expect(document).toEqual(fullDocument());
    // Spot-check the float32-sensitive values explicitly.
    expect(document.drawings[0].drawing?.strokes[0].points[0].pressure).toBe(float32(0.75));
    expect(document.nodes[1].color?.x).toBe(float32(0.1));
    expect(document.activeNodeIndex).toBe(1);
  });

  test("full.ui.bin carries toolbar/session and workspace/UI state on Gpen", () => {
    const document = decodeGpen(loadFixture("full.ui.bin"));
    expect(document.toolbarState?.activeToolId).toBe("draw");
    expect(document.toolbarState?.activeWorkspaceName).toBe("Drawing");
    expect(document.toolbarState?.workspaceStates).toHaveLength(1);
    expect(document.toolbarState?.workspaceStates[0]?.lastBrushPresetId).toBe("brush.ink");
    expect(document.workspaceUi?.name).toBe("Drawing");
    expect(document.workspaceUi?.activeSpaceType).toBe(1);
    expect(document.workspaceUi?.activeToolRef?.idname).toBe("builtin.draw");
    expect(document.workspaceUi?.panels[0]?.toolRef?.idname).toBe("builtin.layers");
    expect(document.workspaceUi?.layout).toContain('"version":1');
  });

  test("owned.bin decodes to a DrawingSlot with only the drawing payload", () => {
    const document = decodeGpen(loadFixture("owned.bin"));
    expect(document.drawings).toHaveLength(1);
    expect(document.drawings[0].reference).toBeNull();
    const stroke = document.drawings[0].drawing?.strokes[0];
    expect(stroke?.id).toBe("stroke-owned-1");
    expect(stroke?.points).toHaveLength(2);
    expect(stroke?.points[0].pressure).toBe(float32(0.5));
    expect(stroke?.points[1].pressure).toBe(float32(0.8));
    expect(stroke?.softness).toBe(float32(0.25));
    expect(stroke?.endCap).toBe(0);
  });

  test("reference.bin decodes to a DrawingSlot with only the reference payload", () => {
    const document = decodeGpen(loadFixture("reference.bin"));
    expect(document.drawings).toHaveLength(1);
    expect(document.drawings[0].drawing).toBeNull();
    const reference = document.drawings[0].reference;
    expect(reference).not.toBeNull();
    expect(reference?.type).toBe(1);
    // uint64 is carried as a bigint through the JS accessor; the fixture value
    // 2^53 + 1 proves the path beyond Number.MAX_SAFE_INTEGER.
    expect(reference?.idReference).toBe(9007199254740993n);
  });

  test("invalid fixtures still decode to their structural object contents", () => {
    const both = decodeGpen(loadFixture("invalid-drawing-slot-both.bin"));
    expect(both.drawings[0].drawing).not.toBeNull();
    expect(both.drawings[0].reference).not.toBeNull();

    const empty = decodeGpen(loadFixture("invalid-drawing-slot-empty.bin"));
    expect(empty.drawings[0].drawing).toBeNull();
    expect(empty.drawings[0].reference).toBeNull();

    const danglingParent = decodeGpen(loadFixture("invalid-parent-index.bin"));
    expect(danglingParent.nodes[1].parentIndex).toBe(7);
  });
});
